[package]
name = "dcal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15"
dasp = "0.11.0"
rb = "0.4"
rubato = "0.12"
symphonia = { version = "0.5", features = [
    "aac",
    "flac",
    "mp3",
    "isomp4",
    "wav",
    "ogg",
    "vorbis",
] }
tap = "1.0.1"
thiserror = "1.0.40"
tracing = "0.1.37"
