on: [push]
name: CI
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.toml') }}
      - name: Install dependencies
        run: $(command -v sudo>/dev/null && echo "sudo") apt-get install -y libasound2-dev
      - name: Minimal build
        run: cargo build --workspace --no-default-features
      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings
      - name: Build all
        run: cargo build --workspace --all-features
      - name: Test
        run: cargo test
